### ISSUE TITLE
warpctc-pytorch 0.2.0 wheels are broken.

### ISSUE THREAD

**Issue by ysk24ok** [espnet/warp-ctc#31]
```console
[root@677710b2f623 warp-ctc]# pip install warpctc-pytorch==0.2.0+torch13.cuda100
Collecting warpctc-pytorch==0.2.0+torch13.cuda100
  Using cached warpctc_pytorch-0.2.0%2Btorch13.cuda100-cp37-cp37m-manylinux1_x86_64.whl (2.7 MB)
Installing collected packages: warpctc-pytorch
Successfully installed warpctc-pytorch-0.2.0
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/opt/pyenv/versions/3.7.9/bin/python3.7 -m pip install --upgrade pip' command.
[root@677710b2f623 warp-ctc]# cat run.py
import torch
from warpctc_pytorch import CTCLoss
ctc_loss = CTCLoss()
probs = torch.FloatTensor([[[0.1, 0.6, 0.1, 0.1, 0.1], [0.1, 0.1, 0.6, 0.1, 0.1]]]).transpose(0, 1).contiguous()
labels = torch.IntTensor([1, 2])
label_sizes = torch.IntTensor([2])
probs_sizes = torch.IntTensor([2])
probs.requires_grad_(True)  # tells autograd to compute gradients for probs
cost = ctc_loss(probs, labels, probs_sizes, label_sizes)
cost.backward()
[root@677710b2f623 warp-ctc]# python3 run.py
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    cost.backward()
  File "/opt/pyenv/versions/3.7.9/lib/python3.7/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/pyenv/versions/3.7.9/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: function _CTCBackward returned an incorrect number of gradients (expected 8, got 7)
```

Because the change introduced by https://github.com/jnishi/warp-ctc/pull/5 is not in SeanNaren/warp-ctc, https://github.com/espnet/warp-ctc/pull/27 breaks the compatibility.

Fixing this bug is simple; just add one more `None` in `CTCLoss.backward`. But I think we should add a test to ensure backward can work correctly.

**Comment by ysk24ok** [comment]
I've created https://github.com/SeanNaren/warp-ctc/pull/178 to add the test because I think the original repository also needs this.
If it's not merged soon, I'm going to create the same PR to this repository.
